name: Publish site workflow

on: [push, workflow_dispatch]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build tailwindcss
        run: |
          npx tailwindcss -i ./src/input.css -o ./dist/tailwind.css

      - name: minify site
        run: |
          sudo apt update
          sudo apt install minify
          minify -r -v $BUILD_DIR -o $BUILD_DIR

      - name: show files
        run: tree

      - name: deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
